### ISSUE TITLE
i tried installing a vs code extension like a browser i'd be using within visual code and i dont seem to get it right. And this has made running and debugging a bit difficult for me. Please help me out

### ISSUE THREAD

**Issue by oseyemi** [microsoft/vscode-edge-devtools#1096]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by oseyemi** [comment]
Windows 10
Edge  browser
Ought to be running and debugging but isn't doing that

**Comment by captainbrosset** [comment]
Hi @oseyemi, thanks for your feedback. However, in order to investigate the problem, we will need a bit more information from you.
You said the extension makes it hard to run and debug, what do you mean exactly? Would you be able to describe in more detail the steps that you are taking in VS Code, and the result you are seeing?
