### ISSUE TITLE
css file not changing

### ISSUE THREAD

**Issue by Christne93** [microsoft/vscode-edge-devtools#1228]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by codepo8** [comment]
Can you give us the information what is happening here? Right now, we can't help you.

**Comment by codepo8** [comment]
My guess is that the <link> in the HTML document doesn't point to the styling.css file. Can you check the network tool to see if the CSS is not loaded? If you filter by styles it should show up as read.
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/

In my case here, the layout.css has a "x/" in front of it which means it can't be found, so the network tool shows it as red and the fix is to remove the x/

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/13508/196482555-a386c4fa-9502-404c-9a38-d715969e7a3b.png">


Even better would be to show us your code.
