### ISSUE TITLE
Clipboard functionality does not work on OSX

### ISSUE THREAD

**Issue by viclunam** [microsoft/vscode-edge-devtools#1277]
**Environment:**
 - OS: 
          OSX Ventura 13.0.1 (22A400)
          2.3 GHz Intel Core i5
 - Extension version: 
ms-edgedevtools.vscode-edge-devtools v2.1.1

**Describe the bug:**

When using the development tools inside VSCode, you cannot copy any text, objects, etc.

If you highlight the text and open the context menu, it also does not allow you to copy any values.

If you use the shortcuts for copy, paste, it doesn't work either.

**Comment by captainbrosset** [comment]
Hi, thanks for filing this issue.

In order to help us fix it, could you please provide a little more information? I'm not sure what you mean by "when using the development tools inside VSCode". What tool were you using exactly? What part of the tool did you try to copy/paste?
I tried quickly, and it worked for me when I copied a CSS value from the Styles pane, and also when I copied a string from the Console. I tested on Windows though, so perhaps this is a mac issue only. But it would help us a lot if you could describe your exact steps when you tried to copy something.

Thanks!

**Comment by captainbrosset** [comment]
Thanks for confirming and providing these extra details. This definitely feels like a mac-only bug then. I'll make sure the team is aware and can review this.

**Comment by codepo8** [comment]
This is tracked, thank you for reporting it.

**Comment by lopugit** [comment]
Is this actually fixed? 😲 I still can't ctrl/cmd + any key combos ? :O 

So even like search all command doesn't work from focused devtools pane, I have to click out, and copy pasting doesn't work at all 😭

Thanks guys!!!

**Comment by captainbrosset** [comment]
> This is all open source right I can contribute?

Yes, this is an open source code repository. If you are interested in contributing, please feel free to fork the repo using GitHub and send Pull Requests. We'd love your help.
