### ISSUE TITLE
File not running

### ISSUE THREAD

**Issue by MimoGame** [microsoft/vscode-edge-devtools#1820]
**Environment (please complete the following information):**
 - OS: Windows 11
 - Extension version: 2.1.3

**Describe the bug:**

Whenever i try to open a html file it shows this page: "file:///C:/Users/subranil/.vscode/extensions/ms-edgedevtools.vscode-edge-devtools-2.1.3/out/startpage/index.html".
**Repro steps:**

Open a html project.
**Expected behavior:**

The html file which I want to run should open.
**Additional context:**

**Comment by captainbrosset** [comment]
Can you try to right-click the HTML file in VS Code and click **Open with Edge** > **Open Browser with DevTools**?
See the docs here: https://learn.microsoft.com/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/get-started-right-click-html#step-2-start-devtools-by-right-clicking-an-html-file

Otherwise, you can also set the URL to your HTML file ion the launch.json file, as documented here: https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/launch-json

Let me know if this worked for you.
