### ISSUE TITLE
This extension could be used to bypass Microsoft Family Safety

### ISSUE THREAD

**Issue by yuttai** [microsoft/vscode-edge-devtools#1895]
**Environment (please complete the following information):**
 - OS: Windows 11
 - Extension version: 2.1.3

**Describe the bug:**
Use this extension to open an Edge in Visual Studio Code, and key in the URL blocked by Microsoft Family Safety, and then Edge in Visual Studio Code still shows the webpage...

**Repro steps:**
Use this extension to open an Edge in Visual Studio Code, and key in the URL blocked by Microsoft Family Safety, and then Edge in Visual Studio Code still shows the webpage...

**Expected behavior:**
It shows the page is blocked by Microsoft Family Safety and ask user to get the permission to see the page... 

**Additional context:**

**Comment by captainbrosset** [comment]
Thanks for your feedback. Filing this as an enhancement on our team's backlog for prioritization.

**Comment by vidorteg** [comment]
Hi @yuttai 
and thank you for your comments, it is my understanding that vscode does not provide hooks for the extensions for family safety, so that limits the extension ability to enhance this policies. My recommendation in here is to send the feedback to either vscode or famility safety via Microsoft Feedback app or in the vscode github repository.

I'm not an expert on family safety features but as a workaround it seems you can block vscode in the family safety panel and that should also block access to the extension, I found an article on how to do it in the microsoft answers forums:

https://answers.microsoft.com/en-us/windows/forum/all/how-to-stop-child-accounts-in-family-from-being/22d6d74f-c9ab-4086-a7d9-7323a176ef0e

Thank you for using the Edge Devtools for Vscode extension, please feel free to reactivate the issue if you have new information or if your issue has not been resolved.

**Comment by yuttai** [comment]
> Hi @yuttai 
> and thank you for your comments, it is my understanding that vscode does not provide hooks for the extensions for family safety, so that limits the extension ability to enhance this policies. My recommendation in here is to send the feedback to either vscode or famility safety via Microsoft Feedback app or in the vscode github repository.
> 
> I'm not an expert on family safety features but as a workaround it seems you can block vscode in the family safety panel and that should also block access to the extension, I found an article on how to do it in the microsoft answers forums:
> 
> https://answers.microsoft.com/en-us/windows/forum/all/how-to-stop-child-accounts-in-family-from-being/22d6d74f-c9ab-4086-a7d9-7323a176ef0e
> 
> Thank you for using the Edge Devtools for Vscode extension, please feel free to reactivate the issue if you have new information or if your issue has not been resolved.

Thanks. My current workaround is indeed limiting vscode for the most 15 minutes in the family safety...
