### ISSUE TITLE
Coloti nell'editor

### ISSUE THREAD

**Issue by Pierfrancescco** [microsoft/vscode-edge-devtools#1964]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by Pierfrancescco** [comment]
Non vedo più i colori che differenziano le classi dalle variabili o funzioni dopo l'ultimo aggiornamento

**Comment by captainbrosset** [comment]
Thank you for reaching out about this. However, it's a little bit hard to know what the problem is without more information first. Can you please answer the following questions:

- Does the problem occur only with the VS Code Edge DevTools extension?
- Does the lack of colors occur in the VS Code text editor, or in an area of the DevTools user interface?
- If in DevTools, where in DevTools exactly?
