### ISSUE TITLE
Create spec to integrate Edge DevTools Extension with VSCode-JS-Debug extension

### ISSUE THREAD

**Issue by mliao95** [microsoft/vscode-edge-devtools#294]
This spec should outline:
- extent of integration
- entry points from VSCode to the DevTools extension
- needed communication between the two extensions

@codepo8  - To work on the vision of integrating the two extensions.
@mliao95 / @vidorteg  - To work on the technical aspects of integration.

**Comment by aaronpowell** [comment]
Just came across this problem myself and wanted to share my thoughts on the workflow that would be ideal (and the current approach).

As a user I want to run my web app with the debugger so that I can inspect the styles and debug JS within one Edge instance. But currently, you need to launch two instances of Edge, one to debug the JS and the other (which was launched by the extension) to use the inspector/network tab.

I'm assuming that this is because the extension captures everything on the devtools protocol socket, overriding the built-in JS debugging features of VS Code.

I started having a dig around with this and then realised I a) need to learn how the devtools protocol works, b) need to learn how the extension works and c) need to learn how VS Code's JS debugger works 😅.

**Comment by mliao95** [comment]
We have actually already completed this functionality! I'm not entirely sure if our documentation is updated, but I can give some quick instructions here.

First, this is currently only available in the nightly build of js-debug, so you can test it out by [enabling the js-debug nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension).  From here, you can now attach the DevTools to an active js-debug section through a new entry point in the connection toolbar as seen in this GIF:

![inspectEntryDemo](https://user-images.githubusercontent.com/14304598/120959686-33a7bd80-c70f-11eb-81af-e3d42e4bd00b.gif)

Going to close this issue since the work here has already been done. Feel free to ask any questions if you have trouble getting this working.

**Comment by aaronpowell** [comment]
Oh nifty, I'll have a play with it
