### ISSUE TITLE
iframes are shown as targets on the side-panel

### ISSUE THREAD

**Issue by vidorteg** [microsoft/vscode-edge-devtools#317]
- Open the extension
- Navigate to a page with iframes (e.g cnn.com)
- A huge list of iframes appear on the target list
![image](https://user-images.githubusercontent.com/43078681/112388460-69144180-8cb0-11eb-87e8-de6c1e5ed6dd.png)

**Comment by flynnolivia** [comment]
I could take a look at this. What's the expected behavior, do we want the iframes to go inside the treeItem for the target it belongs to?

**Comment by vidorteg** [comment]
@codepo8  @mliao95  what do you think, IMO this could get cluttered really fast and I don't see any real value on having it displayed in here. thoughts?

**Comment by mliao95** [comment]
I was thinking that we could use a better filtering workflow for our targets pane instead of either hiding or using settings.
My idea is that we could add multiple checkboxes at the top of the target list like this:
![image](https://user-images.githubusercontent.com/14304598/113029351-2d122e00-9141-11eb-9fc7-ddf563dacabe.png)

The checkboxes would trigger a refresh and would only show the selected checkbox types.  What do you all think?
