### ISSUE TITLE
settings.json file

### ISSUE THREAD

**Issue by William1947** [microsoft/vscode-edge-devtools#375]
{"setting1": 'value',
"setting2": "another value"
}
Trying to find the value of the first 2 lines in settings.json, but nothing seems to work. Still receiving error that the file is invalid and unknown configuration setting. using Visual Studio Code with all updates in windows 10 with all updates.  These two lines changed on my and now I be at a complete loss.

**Comment by codepo8** [comment]
Hello William,

first of all sorry for the delay. It is tough to see what the issue here is from this example alone. Could you give is a full example of your launch.json and check if the debug console has any information? 

On first glance, it may he the single quotes ' around the value instead of double quotes.

**Comment by William1947** [comment]
Hello Christian,  thank you for your concern but I found a way to uninstall Visual Studio Code totally and reinstall it, now working fine, but thank you for the message.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
