### ISSUE TITLE
Elements tool always opens to the right and not where I last placed it

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#44]
When I open a new instance of the Elements tool it always opens a new tab to the right of my current tab. It doesn't remember the last place I put it and open it there.
![image](https://user-images.githubusercontent.com/33229964/59390127-342a3b00-8d25-11e9-9dd1-5e2906788476.png)

**Comment by vidorteg** [comment]
What is the expected behavior in here in the following scenario:

VSCode:
| Tab 1 | Tab 2| Tab 3| Devtools extension | Tab 5|

*close and open devtools*

Possible outcomes:

1. Devtools extension opens in "Tab 4"
1. Devtools extension opens next to the active tab

IMO number 2 is the best option as it shows a consistent behavior with other extensions.

**Comment by codepo8** [comment]
Yes, I also opt for 2.

**Comment by codepo8** [comment]
Can we set option 2?
