### ISSUE TITLE
VS code Run and Debug problem

### ISSUE THREAD

**Issue by richiephp** [microsoft/vscode-edge-devtools#471]
**Environment (please complete the following information):**
 - Windows 10 x64
 - Extension version [e.g. 22]
I don't know what you mean by extension number of Windows

**Describe the bug:**

Run and Debug window does not look normal as compared to laptop

**Repro steps:**

Clicked on the Run and Debug tab to get to the debug window

**Expected behavior:**

To be the normal version of Run and debug

**Additional context:**

By the looks of things the Run and debug on my desktop didn't stop running if that is any indication as to what has gone wrong

![runDebugDesktop](https://user-images.githubusercontent.com/34039916/130367063-851edba1-6d3a-4413-8145-15508544df75.jpg)

Its nots suppose to show the variables, watch and callstack when the debug and run has stopped running

**Comment by richiephp** [comment]
This is how the normal window is suppose to look like under Run and Debug
https://code.visualstudio.com/Docs/editor/debugging
It should be the second picture under Launch Menu, when clicked it should come up with selections to launch either Chrome or Edge

**Comment by bgoddar** [comment]
Thanks for reporting! My understanding is this is "by design" and visual studio code defaults to this view whenever you have a launch.json already configured. The "Run and Debug" buttons are only present when your workspace does not have a launch.json, and the Play button at the top will give you the same functionality as the "run and debug" button.

If you would like to see changes in this behavior, please file a bug over at https://github.com/microsoft/vscode/issues/new/choose
