### ISSUE TITLE
URL is not changing

### ISSUE THREAD

**Issue by renushreeg** [microsoft/vscode-edge-devtools#491]
**Environment (please complete the following information):**
 - OS: Windows
 - Extension version v1.3.0

**Describe the bug:**

When we move along different pages, URL is not getting updated. It's not changing.

**Repro steps:**

Run any react app which has multiple routes.

**Expected behavior:**

URL should get updated automatically

**Additional context:**

When I'm in signin or signup page, URL is static.
![Screenshot 2021-09-13 103032](https://user-images.githubusercontent.com/63147175/133026581-19208ebc-2957-48f0-b051-9b5265da2b01.png)
![Screenshot 2021-09-13 103014](https://user-images.githubusercontent.com/63147175/133026584-5c5d930e-abf4-4f31-8313-713e49645572.png)

**Comment by antross** [comment]
Thanks for the report @renushreeg!

Looks like URL updates from the history API aren't getting picked up. I suspect this is because the current screencast is only responding to the [Page.frameNavigated CDP event](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameNavigated). We should be able to fix this by also listening for [Page.navigatedWithinDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-navigatedWithinDocument).

**Comment by antross** [comment]
FYI @bgoddar

**Comment by antross** [comment]
FYI @bgoddar

**Comment by captainbrosset** [comment]
@antross should the `tracked` label be added so we track this in the internal backlog?

**Comment by mliao95** [comment]
Since this bug was filed, we have a new standalone screencast that lives in its own VSCode tab.  Internal navigation events seem to be handled properly.  Closing this issue.
