### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by LucasOe** [microsoft/vscode-edge-devtools#531]
**Environment (please complete the following information):**
 - OS: Windows 10, Version 21H1
 - Extension version: v1.3.1

**Describe the bug:**
Changing the `vscode-edge-devtools.themes` setting to `dark` doesn't change the theme of the developer tools, even after a restart. Changing the theme using Ctrl+Shit+P also doesn't work.
Note: The addition of new Themes in Microsoft Edge version 93 may has caused this bug (https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/theme).

**Repro steps:**
1. Change `vscode-edge-devtools.themes` to  `dark`
2. Open a new Microsoft Edge Instance, or attach an existing instance to target

**Expected behavior:**
The dev tools inside VSCode should be displayed in a dark theme.

**Additional context:**
![Code_B0kWjfkyYw](https://user-images.githubusercontent.com/16548335/135293637-c95b3aaf-5e54-42af-a9c1-c86c7c1f3866.png)

**Comment by Enteleform** [comment]
Same issue here.

**Comment by NeriDarkira** [comment]
same issue here, but I think I found a "solution":
in one of the last updates EdgeDevTool started getting the theme directly from the vsCode-theme; so, if you have on of the [available themes](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/theme), the EdgeDevTool will "follow" that theme.
if you don't use one of the supported ones, EdgeDevTool will follow the default theme (light).

So if you wanna change the theme you have to change the vsCode theme in one of the supported, 'till they fix this issue ( get default from settings "vscode-edge-devtools.themes" instead of automatically switch to light)

**Comment by LucasOe** [comment]
@NeriDarkira I was able to fix the problem.

[Here](https://github.com/microsoft/vscode-edge-devtools/blob/706bc60c690b9db2932c4595a9ecd5b030827e66/src/devtoolsPanel.ts#L486) the theme gets passed as an URL argument. Passing `Dark` as a capitalized string doesn't work. Using the legacy function `getThemeSettings()` instead of `getThemeFromUserSetting()` and changing `Dark` to `dark` as a setting in the package.json fixes the problem.

This works for now, I'm not sure how to make use of the new dev tools themes introduced in version 93 however.

**Comment by vidorteg** [comment]
I still see this issue on the latest version so reopening it.

I think that this bug are actually two different issues spotted correctly by @NeriDarkira and @LucasOe 
1. On the latest versions `getThemeFromUserSetting` should default to 'systemPreferred' not 'System preference'
2.  This line:
 `return SUPPORTED_THEMES.get((themeSetting || legacySetting))` 
should be:
 ` return SUPPORTED_THEMES.get(themeSetting) || SUPPORTED_THEMES.get(legacySetting)`
 
 Thanks everyone for the comments, I'll take a look to the PR set up in here:
 https://github.com/microsoft/vscode-edge-devtools/pull/567/files

so that we can get this fixed soon :)
