### ISSUE TITLE
Error while trying to edit css (.less file) in the Edge DevTools 

### ISSUE THREAD

**Issue by RadhiRasho** [microsoft/vscode-edge-devtools#557]
**Version:**
        1.3.1

        **OS:**
        
Microsoft Windows

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://localhost:8080/quotations.less'.

        **Additional context:**
        
I use `.less` files for my css and it couldn't source map it to the correct file.

**Comment by captainbrosset** [comment]
Let's mark this as tracked since this is being worked on.

**Comment by mliao95** [comment]
This is fixed in the newer versions of Edge starting at version 102.0.1216.0.  This will hit all Edge browsers near the end of May, but you can try out sourcemapping support now by downloading Edge Canary from [here](https://www.microsoftedgeinsider.com/en-us/download) and then switch which Edge channel you want to use in the settings by searching for "Browser flavor" and choosing 'Canary' from the dropdown:

![image](https://user-images.githubusercontent.com/14304598/160931870-322840da-45be-4345-b453-e907d419d4ed.png)

If you have any more questions, please let me know.  I am going to close out this issue.
