### ISSUE TITLE
Please support none-IDE mode 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-edge-devtools#56]
> alter layout, and fix styling issues. All without leaving VS Code.

That made me cry a little. Many users of VS Code like it to be an editor, not an IDE. I personally don't see a reason why VS Code should replicate the contents of a website in a tiny embedded widget and from my experience I am not the only user that thinks like this. 

So, please consider a none-IDE integration along the full IDE mode. In my ideal world it would work like this:

* Show browser-things in the browser, e.g the elements tab, the performance tools etc
* Show source code in VS Code, e.g when I select `styles.scss` inside dev tools, then open that file in VS Code. If picking a color updates a file, do that with VS Code (there is API for all of that)

I hope all of that makes sense, feel free to get in touch with me, and in case a none-IDE integration already exists please ignore this. Anyways please don't forget those VS Code users that like pressing Alt/Cmd-Tab and that like OS window managers, they do exist.

**Comment by paulgildea** [comment]
@jrieken Thanks for the feedback!

This extension is only the Elements tool. Since there is already a Debugger/Console extension: [Debugger for Edge](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge) we wanted to experiment with having the most commonly used tools (Elements, Console, Debugger) within VS Code and get customer feedback. So again, thanks for the feedback 😊.

The Elements tool is our current focus and currently do not have plans to move all the tools within VS Code. So to your point - we also feel some tools belong in the browser and some tools could live in Editors like VS code, but where it makes sense. 

As a principle, we want to have as similar experiences as we can across the browser DevTools and any tool integrations we may build. 

I am super interested in your second bullet point 😊. So a couple questions:

1. In your ideal experience, when you click on a link in the Styling Pane, would you prefer to have it open in VS Code vs. the Sources tab in the browser? By default? Right-click context menu option? A setting you enable in the Settings Panel?
2. If the source mapping is incorrect would you prefer to have it fall back on the Sources tab or error out?
3. Would you prefer to open JavaScript files and set breakpoints in VS Code vs. Sources tab? Basically, have the same "Open files in my Editor" experience for all files?

Again thanks for the feedback! We're super curious about how folks are using their Editors and the Edge Browser together to build out their web experiences.

**Comment by jrieken** [comment]
> In your ideal experience, when you click on a link in the Styling Pane, would you prefer to have it open in VS Code vs

Always VS Code! At least when I have started in VS Code, e.g when I launch Edge from VS Code I would expect to get back to it for editing source files. Actually, I want that for all source file links, e.g. links in the performance or memory tab. Having more options in the context menu is always good, esp. when I have started in Edge itself.

> If the source mapping is incorrect would you prefer to have it fall back on the Sources tab or error out?

I am not a fan of source maps and try to avoid them at all costs, e.g I turn them off whenever possible. Tho, assuming I would use them and assuming the mapping is defunct, I would still expect the underlying (JS/css) file to open in VS Code, e.g. you can register a file system for the "real" (unmapped) files and show them in VS Code. 

> Would you prefer to open JavaScript files and set breakpoints in VS Code vs. Sources tab? Basically, have the same "Open files in my Editor" experience for all files?

That's good a question. Today, I use the source tab and set breakpoints in JS files (no source maps, see above) but that actually feels clunky. Ideally, I can do both, e.g set breakpoints in TS files in VS Code (and they make their way down to the JS files) and set breakpoints in JS files, also in VS Code. In short, debugging is (should be) part of my inner loop and for that I should be in VS Code

**Comment by paulgildea** [comment]
Love it! This is great feedback.

> Always VS Code! At least when I have started in VS Code, e.g when I launch Edge from VS Code I would expect to get back to it for editing source files. Actually, I want that for all source file links, e.g. links in the performance or memory tab. Having more options in the context menu is always good, esp. when I have started in Edge itself.

I've added a feedback item via the Edge Send-a-Smile with a link to this issue to collect this feedback on in browser tools.

> I am not a fan of source maps and try to avoid them at all costs, e.g I turn them off whenever possible. Tho, assuming I would use them and assuming the mapping is defunct, I would still expect the underlying (JS/css) file to open in VS Code, e.g. you can register a file system for the "real" (unmapped) files and show them in VS Code.

I'd like to follow up to understand your workflow here. So I'll reach out for that.

Thanks again!

**Comment by codepo8** [comment]
Seems follow-up happened as this was internal
