### ISSUE TITLE
Error: Couldn't attach to about:blank

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode-edge-devtools#57]
Tried extension with a React app and an Angular app running in VScode Version 1.36.0-insider (1.36.0-insider) via npm script explorer.  Edge Version 77.0.204.0 (Official build) Canary (64-bit) alrady running, displaying the app.

Click sidebar icon for Edge Elements, click the plus icon.  

A new tab opens in Edge, but all I get is this:

<img width="477" alt="Screen Shot 2019-06-28 at 12 23 26 PM" src="https://user-images.githubusercontent.com/835148/60356938-469ca980-99a0-11e9-873b-b35da7862e5a.png">

**Comment by paulgildea** [comment]
Bummer. Do you know if the instance of Edge running is using `--remote-debugging-port=9222`? That needs to be enabled so that it can connect over CDP.

**Comment by smlombardi** [comment]
No, it’s just a regular instance of Edge, opened in the finder. The apps are just running with `ng serve`

**Comment by paulgildea** [comment]
Try:
1. Open a new Terminal window
2. Run - `/Applications/Microsoft\ Edge\ Canary.app/Contents/MacOS/Microsoft\ Edge\ Canary --remote-debugging-port=9222` This should hopefully open Edge with remote debugging enabled.
3. Navigate to your localhost app
4. Press the Refresh button in the Elements for Edge Side Panel

Hopefully your that tab will show up in the list.

**Comment by smlombardi** [comment]
Yes, that works.  Will this always be the case?  Seems like a rather cumbersome way to use it.

**Comment by paulgildea** [comment]
The key is that the browser needs to be running with remote debugging enabled and that happens when it's launched. There are a couple of options to help smooth out the experience:

## 1. Close all browser instances before your initial debugging loop
If you don't have any running instances of the browser, pressing the (+) icon will launch the browser in remote debugging mode on 9222. Subsequent (+) icon presses will launch a new tab in that running instance, (assuming it's still in remote debugging mode.)

## 2. Add a Default Url
![image](https://user-images.githubusercontent.com/33229964/60436810-bb9af980-9bc1-11e9-8a29-81e88246f0ab.png)
In the VS Code Settings you can specify a Default Url to navigate to a specific page when the (+) icon is pressed. This removes the manual typing the browser step. In the above screenshot it should navigate to localhost:8080. If no Url is provided it just navigates to about:blank. This assumes you did option 1 above.

## 3. Add a User Data Directory
![image](https://user-images.githubusercontent.com/33229964/60437021-3bc15f00-9bc2-11e9-8795-d726bda9c455.png)
In the VS Code Settings you can specify a User Data Directory to be used. This will open a new separate  instance of Edge using that new directory for user data. Some folks like this option because they can have a specific debug profile that's separate from their everyday browsing profile.

Let us know if any of those options help! 😊

**Comment by smlombardi** [comment]
Thanks

1. Can these settings be workspace instead of user?  Different projects might be on different ports on localhost
2. At some point it would be nice to launch a new instance on Edge in debug mode when you click "+", like it does when you are launching a debug session in Chrome.

**Comment by paulgildea** [comment]
> Can these settings be workspace instead of user? Different projects might be on different ports on localhost

Interesting suggestion. We can add that to our list of settings. Do you find yourself bouncing between a lot of different projects?

> At some point it would be nice to launch a new instance on Edge in debug mode when you click "+", like it does when you are launching a debug session in Chrome.

This is great feedback. We've been debating what the right default behavior should be. In your opinion, would you want it launch a new instance of Edge every time you press the (+) icon?

I'm going to rename this issue to the more general "error" folks encounter so propose more discussion.

**Comment by smlombardi** [comment]
Yes, I am often working on 2-3 projects at once.  In some cases each one has a different port.

I would expect + to open a new Edge each time.  I'd expect to have to close the "extra" instance on Edge in debug mode by closing the window.  It's similar to Chrome debugging:  I have Chrome open with a bunch of unrelated tabs.  In VSCode, I switch to Debug mode and click to launch Chrome for debugging.  A new window opens with my breakpoint etc.  When I'm done debugging I close this window and go on with my norma Chrome usage.

**Comment by fiveisprime** [comment]
Opening a new instance make sense to me - that's the behavior I get from the [Debugger for Edge](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge) today so I'm quite used to that experience.

**Comment by hxlnt** [comment]
> The key is that the browser needs to be running with remote debugging enabled and that happens when it's launched. There are a couple of options to help smooth out the experience:
> 
> ## 1. Close all browser instances before your initial debugging loop

Is there a place where this is documented, and/or should it be tracked as a separate bug? I ran into similar problems ("Couldn't attach to about:blank" or "Couldn't attach to http://localhost:8080") on my PC until I closed all Edge tabs and _then_ executed the launch command from VS Code.

**Comment by paulgildea** [comment]
@hxlnt - This is the place right now 😊. @jalissia is working on a PR to update the default behavior to opening a new Edge instance and provide updates to the README indicating so. 

@smlombardi and @fiveisprime this is great feedback. Thanks!

Since you both mentioned debuggers... I had some addition questions I'd like to get your feedback on if you don't mind. I'll open a new issue and at mention folks here. And this issue will close once the PR goes through.

**Comment by jalissia** [comment]
The above PR should fix the first launch failing to attach experience. It will end up popping a new window instance in the same way that the chrome and edge debug extensions do.
