### ISSUE TITLE
Not working on disconnected network

### ISSUE THREAD

**Issue by tomer953** [microsoft/vscode-edge-devtools#649]
**Environment (please complete the following information):**
 - OS: Windows 10
 - Extension version: 1.4.1

**Describe the bug:**

the extension is not working under offline\disconnected network, due to the need of:
https://devtools.azureedge.net/serve_file/ 

the following error is appear:
https://github.com/microsoft/vscode-edge-devtools/blob/08cef848fd7e18f8c06b4f8572fe42a72b611a0e/src/devtoolsPanel.ts#L467

any chance for disconnected computers to workaround this issue?

**Comment by codepo8** [comment]
Thanks for this, looking into adding this as an enhancement in the future

**Comment by mliao95** [comment]
This feature should be available in the latest version of the extension

**Comment by tomer953** [comment]
> This feature should be available in the latest version of the extension

Thank you, but still no luck for me.

I've installed 1.4.7 from the marketplace, and same problem.

`Unable to download DevTools for the current target`

I also unzipped the vsix, and I can still see that function:
https://github.com/microsoft/vscode-edge-devtools/blob/main/src/devtoolsPanel.ts#L521

my disconnected network cannot fetch this url, so its fail

**Comment by mliao95** [comment]
Hey @tomer953,

Thanks for reaching out.  This is how our disconnected session works. When you have internet, the extension remembers the last known valid connection to the DevTools and service workers on the DevTools side caches the files retrieved from the `https://devtools.azureedge.net/serve_file/` link. The next time you open the DevTools offline, you will try connecting to the same `https://devtools.azureedge.net/serve_file/` link, but instead of trying to retrieve the files from the URL, it will grab it from your local cache.

Try this workflow:
- With internet: Use our extension and launch an instance of the DevTools
- Disconnect from internet
- Use our extension and launch an instance of the DevTools

Let me know if this flow is still broken for you.

**Comment by tomer953** [comment]
Hi, thanks for the help. 

However, it might sound strange - but we cannot access to the internet at all in the discussed development pc. 
We can transfer data in form of files, but other then that they are completely disconnected. (Security reasons)

As i see it, we can solve with:

copy the cache files from a connected computer to the disconnect pcs. (I will need a little hint of what to copy) - the main cons is that the installation process for each disconnected pc is a little hard. 

The other option is to a configuration setting to define the url that being used for the fetch - this is also being tricky, because we will need to self host the entire files as a website, and im not sure if its easy to just clone everything. 

The last and best for us obviously, is that the extension itself will packed with  a cache copy of everything needed, and will refresh it if can. 

thought?
