### ISSUE TITLE
Scroll-behavior = smooth

### ISSUE THREAD

**Issue by Felippefn** [microsoft/vscode-edge-devtools#680]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codepo8** [comment]
Hello Felippe, could you tell us more what you are missing or hat the issue is?

**Comment by Felippefn** [comment]
Hi.. apparently you can’t use the smooth-scroll with Microsoft Edge, and I really would like to know more about it. Thank you very much for your attention!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by codepo8** [comment]
Hi there, 
your issue seems to be with Edge, the browser, not with this extension. However, it does work here. If you go to my demo page and hit any of the "cats, dogs, sheep…" items you will see that the page scrolls down smoothly.
https://codepo8.github.io/a11y-demos/page-with-errors.html 

Could it be that you turned off animations in your OS/your device or that you have the simulation turned on?

https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-reduced-ui-motion
