### ISSUE TITLE
HTML code error

### ISSUE THREAD

**Issue by ImToddthegod990** [microsoft/vscode-edge-devtools#792]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

When i press "EDIT AS HTML" It does not show or screen goes blank
**Repro steps:**

In edge dev tools i right click an html and i press edit as HTML then that leads to the problem
**Expected behavior:**

It shows the full HTML code to the Web/TAB
**Additional context:**

![image](https://user-images.githubusercontent.com/79087136/147993685-7f3ce2a9-4da0-47fc-a199-0c3c005b3002.png)

**Comment by mliao95** [comment]
This is fixed in the newer versions of Edge starting at version 101.0.1198.0. This will hit all Edge browsers on 4/28, but you can get the fixed version now by downloading either Edge Canary or Edge Dev from [here](https://www.microsoftedgeinsider.com/en-us/download) and then switch which Edge channel you want to use in the settings by searching for "Browser flavor" and choosing from the dropdown:

![image](https://user-images.githubusercontent.com/14304598/160931870-322840da-45be-4345-b453-e907d419d4ed.png)

If you have any more questions, please let me know.  I am going to close out this issue.
