### ISSUE TITLE
Modify in the devtools did not save in the original source files

### ISSUE THREAD

**Issue by liudonghua123** [microsoft/vscode-edge-devtools#92]
I wonder if I can make changes in the devtools and auto save the changes in the original source files. If this is possible, how can I achieve it.

**Comment by jalissia** [comment]
Thanks for the feedback, but unfortunately not yet. The closest experience you can get at the moment is clicking the links in the styles panel and having that open up your source file (assuming you have source maps set up correctly).

You can then use some other utility such as browser-sync to auto refresh the page when you change your source css file.

That would give you something like the following:
![elements-css-mapping](https://user-images.githubusercontent.com/10660853/63452736-d9cfe980-c3fb-11e9-8241-635ecc204797.gif)

Here I am clicking on the `background-color` property in the styles pane, which opened up my source scss file to the correct line. I then edited the scss file to use `red` and saved the file, which in turn (due to browser-sync) auto refreshed the page.

We are still investigating what it would take to have a better experience around interacting with the actual source from this extension.

**Comment by liudonghua123** [comment]
@jalissia Thanks, I will try your suggestions and keep an eye on the similar features. 😃

**Comment by codepo8** [comment]
Thanks for your feedback. It seems the solution described above fixes the problem for now. It would be interesting for us to see what other functionality you'd like to see there. I am not sure that automatically saving all the changes would be the right solution as it does mess with the version control of the main file.
