### ISSUE TITLE
Edge extension opening console in foreground

### ISSUE THREAD

**Issue by AuracleTech** [microsoft/vscode-edge-devtools#976]
**Is your feature request related to a problem?**
*I believe* that since I downloaded Edge vscode extension, this pops up randomly.
I think it has to do with nodejs hint-configuration.
Either way, it's **really getting on my nerves**

![image](https://user-images.githubusercontent.com/40531871/163267035-b9857c21-5381-4bf0-9297-ca5d33ac57e7.png)

**Describe the solution you'd like:**
Run it in the background

**Describe alternatives you've considered:**
Uninstalling the extension, but I can't for now.

**Comment by antross** [comment]
Thanks for the report @AuracleTech! I've seen this recently too and it is annoying.

I don't think VS Code used to pop this into the foreground so something must have changed that we likely need to adapt to. This happens when we're trying to update webhint so we could at least make some adjustments to reduce the frequency of checks reduce the annoyance. Still, it'd be great if we could keep this from popping up altogether.

@codepo8 what do you think?

**Comment by mungojam** [comment]
This has been worrying me that I've got a virus for days

**Comment by TheBrenny** [comment]
> This happens when we're trying to update webhint so we could at least make some adjustments to reduce the frequency of checks reduce the annoyance.

Obviously, doing it in the background is optimal, but how often does Webhint need to be updated? I get this so frequently it feels like it happens every 3 times I bring vscode into the foreground.

(P.S. Can we add tags to this issue so it gets a higher SEO on Google, or at least add more keywords? I had to `grep -rail` my extensions to figure out who the culprit was. 😞)
